Repository Succery-dev/Qube, pull requests merged in 2023-07, with the labels that each got.

#127 Create POST API to store project data on cloud firestore
  frontend/components/project/CreateProjectForm.tsx
  frontend/enums/projectStatus.ts
  frontend/pages/api/project/index.ts
Labels: prio:normal, type:backend

#128 Feature/fetch data dashboard
  frontend/components/dashboard/Table.tsx
  frontend/constants/mockData.ts
  frontend/interfaces/dashboard/projectData.ts
  frontend/interfaces/dashboard/projectDetail.ts
  frontend/pages/api/project/[walletAddress].ts
  frontend/pages/api/project/index.ts
  frontend/pages/dashboard/[walletAddress].tsx
Labels: prio:normal, type:backend

#129 Fix/status enum
  frontend/constants/mockData.ts
  frontend/enums/projectStatus.ts
  frontend/pages/dashboard/[walletAddress].tsx
Labels: prio:normal, type:backend

#130 Feature/project link
  frontend/components/dashboard/Table.tsx
  frontend/components/project/CreateProjectForm.tsx
  frontend/components/project/ProjectScaffold.tsx
  frontend/pages/api/projectDetail/[projectId].ts
  frontend/pages/project/[projectId].tsx
Labels: prio:normal, type:backend

#131 Kunal137/feature/nft gated
  frontend/assets/Icon-Copy.svg
  frontend/assets/Icon-Dropdown.svg
  frontend/assets/index.ts
  frontend/components/Navbar.tsx
  frontend/components/Notification.tsx
  frontend/components/index.ts
  frontend/components/project/3d/Logo3D.tsx
  frontend/components/project/3d/index.ts
  frontend/components/project/CreateProjectForm.tsx
  frontend/components/project/CreateProjectModal.tsx
  frontend/components/project/ProjectScaffold.tsx
  frontend/components/project/index.ts
  frontend/components/projectDetails/Dropbox.tsx
  frontend/components/projectDetails/ProjectDetails.tsx
  frontend/components/projectDetails/ProjectDetailsDescription.tsx
  frontend/components/projectDetails/SubmitTextArea .tsx
  frontend/components/projectDetails/index.ts
  frontend/constants/index.ts
  frontend/context/Project.tsx
  frontend/interfaces/index.ts
  frontend/interfaces/project/createProjectFormInterface.ts
  frontend/interfaces/project/index.ts
  frontend/interfaces/project/nftAddressDetailsInterface.ts
  frontend/interfaces/projectDetails/descriptionProjectDetails.ts
  frontend/interfaces/projectDetails/displayProjectDetails.ts
  frontend/interfaces/projectDetails/displayTextDeliverable.ts
  frontend/interfaces/projectDetails/fileDeliverableInterface.ts
  frontend/interfaces/projectDetails/index.ts
  frontend/interfaces/projectDetails/storeProjectDetails.ts
  frontend/pages/_app.tsx
  frontend/pages/createProject.tsx
  frontend/pages/projectDetails/[projectId].tsx
  frontend/styles/globals.css
  frontend/types/index.ts
  frontend/types/projectDetails/descriptionProjectDetailsInterfaceKeys.ts
  frontend/types/projectDetails/displayProjectDetailsInterfaceKeys.ts
  frontend/types/projectDetails/index.ts
  frontend/utils/createProject/index.ts
  frontend/utils/createProject/verifyNftAddress.ts
  frontend/utils/firebase.ts
  frontend/utils/formatBytes.ts
  frontend/utils/index.ts
  frontend/utils/projectDetail/approveProjectDetails.ts
  frontend/utils/projectDetail/assignProject.ts
  frontend/utils/projectDetail/checkNftOwnership.ts
  frontend/utils/projectDetail/getDataFromFireStore.ts
  frontend/utils/projectDetail/index.ts
  frontend/utils/projectDetail/populateStates.ts
  frontend/utils/projectDetail/updateProjectDetails.ts
Labels: prio:ASAP, type:backend, type:frontend

#132 add page 404
  frontend/components/index.ts
  frontend/components/project/index.ts
  frontend/constants/index.ts
  frontend/pages/404.tsx
  frontend/pages/createProject.tsx
  frontend/styles/globals.css
Labels: prio:low, type:frontend

#134 Fix/errors after PRs
  frontend/assets/index.ts
  frontend/components/index.ts
  frontend/components/project/3d/Logo3D.tsx
  frontend/components/project/CreateProjectForm.tsx
  frontend/components/project/ProjectScaffold.tsx
  frontend/components/project/index.ts
  frontend/pages/api/project/[walletAddress].ts
  frontend/pages/api/project/index.ts
  frontend/pages/api/projectDetail/[projectId].ts
  frontend/pages/createProject.tsx
  frontend/pages/project/[projectId].tsx
  frontend/styles/globals.css
  frontend/utils/firebase.ts
  frontend/utils/index.ts
Labels: prio:high, type:bug

#136 Check verify nft
  frontend/components/project/CreateProjectForm.tsx
  frontend/pages/createProject.tsx
  frontend/utils/createProject/verifyNftAddress.ts
Labels: prio:high, type:backend
